version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: booksdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: leiyu465/books:v1.0.0
    container_name: app-container
    environment:
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: booksdb
      DB_HOST: mysql
      DB_PORT: 3306
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
